#!/usr/bin/env bash
# Install a pre-commit hook that blocks accidental commits of:
#   - .env or any .env.*  (except .env.example)
#   - .dexter/inputs/**/options.md     (user-pasted options data)
#   - .dexter/memory/, .dexter/cache/  (research history)
#   - obvious secret patterns (API keys, bearer tokens)
#
# Idempotent. Re-run safely to refresh the hook.
set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")/.." rev-parse --show-toplevel)"
HOOK="$REPO_ROOT/.git/hooks/pre-commit"

cat > "$HOOK" <<'HOOK_EOF'
#!/usr/bin/env bash
# alpha-probe pre-commit guard — generated by scripts/install-precommit-hook.sh
set -euo pipefail

# Files staged for commit.
staged="$(git diff --cached --name-only --diff-filter=ACM)"
[ -z "$staged" ] && exit 0

fail() {
  echo "" >&2
  echo "[pre-commit] BLOCKED: $1" >&2
  echo "[pre-commit] If you really mean this, run: git commit --no-verify" >&2
  exit 1
}

# 1. Block .env and .env.* files (allow .env.example).
while IFS= read -r f; do
  case "$f" in
    .env.example) ;;
    .env|.env.*) fail "staged secret file: $f" ;;
  esac
done <<< "$staged"

# 2. Block user-pasted options data and trace dirs.
while IFS= read -r f; do
  case "$f" in
    .dexter/inputs/*/options.md) fail "staged options-flow paste: $f (may be licensed broker data)" ;;
    .dexter/memory/*|.dexter/cache/*|.dexter/cron/*|.dexter/HEARTBEAT.md|.dexter/settings.json)
      fail "staged Dexter trace artifact: $f" ;;
  esac
done <<< "$staged"

# 3. Scan staged content for obvious secret shapes.
#    Catches the most common slip; not a substitute for a real secret scanner.
patterns=(
  'sk-ant-api[0-9]{2}-[A-Za-z0-9_-]{20,}'   # Anthropic
  'sk-proj-[A-Za-z0-9_-]{20,}'              # OpenAI project key
  'sk-[A-Za-z0-9]{30,}'                     # OpenAI / generic
  'AIza[0-9A-Za-z_-]{35}'                   # Google
  'xoxb-[0-9A-Za-z-]{40,}'                  # Slack bot
  'AAAA[A-Za-z0-9%]{40,}'                   # X bearer-style
  'fd_[A-Za-z0-9]{30,}'                     # FinancialDatasets-style
)

# Concatenate patterns with | for one grep pass.
joined="$(IFS='|'; echo "${patterns[*]}")"

# Look at staged diff only (so old leaks in history don't keep blocking).
if git diff --cached -U0 | grep -E "$joined" -q; then
  fail "staged content matches a known API-key pattern"
fi

exit 0
HOOK_EOF

chmod +x "$HOOK"
echo "[install-hooks] wrote pre-commit guard to $HOOK"
echo "[install-hooks] test with: git commit (will block on .env / secrets / options.md)"
